In [2]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns

# dataset
**Link**--->https://www.kaggle.com/datasets/prasenjitsharma/hearing-test-classification-problem

In [5]:
#importing dataset
df=pd.read_csv('hearing_test.csv')
df.head()

age  physical_score  test_result  db  gender
0  33.0            40.7            1  16       0
1  50.0            37.2            1  15       0
2  52.0            24.7            0   9       0
3  56.0            31.0            0   0       0
4  35.0            42.9            1   9       0

In [7]:
#checking for null values
df.isnull().sum()

age               0
physical_score    0
test_result       0
db                0
gender            0
dtype: int64

In [8]:
df.describe()

age  physical_score  test_result           db       gender
count  5000.000000     5000.000000  5000.000000  5000.000000  5000.000000
mean     51.607700       32.766980     0.600000    13.473200     0.494000
std      11.282895        8.147737     0.489947     8.538493     0.500014
min      18.000000        8.400000     0.000000     0.000000     0.000000
25%      43.000000       26.700000     0.000000     6.000000     0.000000
50%      51.000000       35.300000     1.000000    13.000000     0.000000
75%      60.000000       38.900000     1.000000    20.000000     1.000000
max      85.500000       50.000000     1.000000    35.000000     1.000000

In [9]:
df['test_result'].value_counts()

test_result
1    3000
0    2000
Name: count, dtype: int64

In [10]:
df.columns

Index(['age', 'physical_score', 'test_result', 'db', 'gender'], dtype='object')

In [11]:
X = df.drop('test_result',axis=1)
y=df['test_result']

In [12]:
from feature_engine.outliers import Winsorizer

win= Winsorizer(capping_method='iqr',variables=['age'],tail='both',fold=1.5)

df['age']=win.fit_transform(df[['age']])

print(win.left_tail_caps_,win.right_tail_caps_)

ModuleNotFoundError: No module named 'feature_engine'

In [13]:
from feature_engine.outliers import Winsorizer

win= Winsorizer(capping_method='iqr',variables=['physical_score'],tail='both',fold=1.5)

df['physical_score']=win.fit_transform(df[['physical_score']])

print(win.left_tail_caps_,win.right_tail_caps_)

ModuleNotFoundError: No module named 'feature_engine'

In [14]:
X.head()

age  physical_score  db  gender
0  33.0            40.7  16       0
1  50.0            37.2  15       0
2  52.0            24.7   9       0
3  56.0            31.0   0       0
4  35.0            42.9   9       0

In [15]:
y.head()

0    1
1    1
2    0
3    0
4    1
Name: test_result, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
# df.to_csv('claimant_clean.csv',index=False)

# from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

#ML models
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [18]:
# decision Tree


DT = DecisionTreeClassifier()
DT.fit(X_train, y_train)
from sklearn.model_selection import cross_val_score

# y_predict = DT.predict(X_test)
print('*'*20)

# prediction
train_pred=DT.predict(X_train)
test_pred= DT.predict(X_test)
print('*'*20)
# accuracy
print('Train accuracy:' , accuracy_score(y_train,train_pred))
print('Test accuracy:' , accuracy_score(y_test,test_pred))

print('*'*20)
 # cross validation   
score= cross_val_score(DT,X,y,cv=5)
print(score)
print(score.mean())

print('*'*20)
#  prediction Summary by species
print(classification_report(y_test, test_pred))

print('*'*20)
# Accuracy score
DT_SC = accuracy_score(test_pred,y_test)
print(f"{round(DT_SC*100,2)}% Accurate")

print('*'*20)



********************
********************
Train accuracy: 0.99925
Test accuracy: 0.886
********************
[0.876 0.869 0.897 0.889 0.876]
0.8814000000000002
********************
              precision    recall  f1-score   support

           0       0.87      0.85      0.86       402
           1       0.90      0.91      0.91       598

    accuracy                           0.89      1000
   macro avg       0.88      0.88      0.88      1000
weighted avg       0.89      0.89      0.89      1000

********************
88.6% Accurate
********************


In [19]:
# random forest

from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier(random_state=42)
rfc.fit(X_train,y_train)
print('*'*20)

# prediction
train_prediction= rfc.predict(X_train)
test_prediction= rfc.predict(X_test)
print('*'*20)

# evaluation
from sklearn.metrics import accuracy_score
print('test accuracy:',accuracy_score(y_test,test_prediction))
print('train accuracy:',accuracy_score(y_train,train_prediction))
print('*'*20)

# cross validation score
from sklearn.model_selection import cross_val_score
score=cross_val_score(rfc,X,y,cv=5)
print(score.mean())
print('*'*20)

#  prediction Summary by species
# print(classification_report(y_test, test_prediction))
print('*'*20)

# Accuracy score
RF_SC = accuracy_score(test_prediction,y_test)
print(f"{round(RF_SC*100,2)}% Accurate")

********************
********************
test accuracy: 0.918
train accuracy: 0.99925
********************
0.9166000000000001
********************
********************
91.8% Accurate


In [20]:

# logistic regression

LR = LogisticRegression()
LR.fit(X_train, y_train)


# prediction
train_prediction= LR.predict(X_train)
test_prediction= LR.predict(X_test)
print('*'*20)

# evaluation
from sklearn.metrics import accuracy_score
print('test accuracy:',accuracy_score(y_test,test_prediction))
print('train accuracy:',accuracy_score(y_train,train_prediction))
print('*'*20)

# cross validation score
from sklearn.model_selection import cross_val_score
score=cross_val_score(LR,X,y,cv=5)
print(score.mean())
print('*'*20)

print(classification_report(y_test,test_pred))

print('*'*20)


lr_HSC = accuracy_score(y_test,test_prediction)
print(f"{round(lr_HSC*100,2)}% Accurate")

********************
test accuracy: 0.92
train accuracy: 0.91425
********************
0.915
********************
              precision    recall  f1-score   support

           0       0.87      0.85      0.86       402
           1       0.90      0.91      0.91       598

    accuracy                           0.89      1000
   macro avg       0.88      0.88      0.88      1000
weighted avg       0.89      0.89      0.89      1000

********************
92.0% Accurate


In [21]:
#  XGBoost

XGB = XGBClassifier()
XGB.fit(X_train, y_train)

# prediction
train_prediction= XGB.predict(X_train)
test_prediction= XGB.predict(X_test)
print('*'*20)

# evaluation
from sklearn.metrics import accuracy_score
print('test accuracy:',accuracy_score(y_test,test_prediction))
print('train accuracy:',accuracy_score(y_train,train_prediction))
print('*'*20)

# cross validation score
from sklearn.model_selection import cross_val_score
score=cross_val_score(XGB,X,y,cv=5)
print(score.mean())
print('*'*20)

print(classification_report(y_test,test_pred))

print('*'*20)


XGB_HSC = accuracy_score(y_test,test_prediction)
print(f"{round(XGB_HSC*100,2)}% Accurate")

d:\Full Stack Course\Visual Studio Code\D-jango.VS\AA\Hearing-loss-setection\hearing_env\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
d:\Full Stack Course\Visual Studio Code\D-jango.VS\AA\Hearing-loss-setection\hearing_env\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
d:\Full Stack Course\Visual Studio Code\D-jango.VS\AA\Hearing-loss-setection\hearing_env\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
d:\Full Stack Course\Visual Studio Code\D-jango.VS\AA\Hearing-loss-setection\heari

********************
test accuracy: 0.918
train accuracy: 0.97575
********************


d:\Full Stack Course\Visual Studio Code\D-jango.VS\AA\Hearing-loss-setection\hearing_env\Lib\site-packages\xgboost\data.py:335: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
d:\Full Stack Course\Visual Studio Code\D-jango.VS\AA\Hearing-loss-setection\hearing_env\Lib\site-packages\xgboost\data.py:338: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  is_categorical_dtype(dtype) or is_pa_ext_categorical_dtype(dtype)
d:\Full Stack Course\Visual Studio Code\D-jango.VS\AA\Hearing-loss-setection\hearing_env\Lib\site-packages\xgboost\data.py:384: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype):
d:\Full Stack Course\Visual Studio Code\D-jango.VS\AA\Hearing-loss-setection\heari

0.913
********************
              precision    recall  f1-score   support

           0       0.87      0.85      0.86       402
           1       0.90      0.91      0.91       598

    accuracy                           0.89      1000
   macro avg       0.88      0.88      0.88      1000
weighted avg       0.89      0.89      0.89      1000

********************
91.8% Accurate


In [22]:
from sklearn.ensemble import AdaBoostClassifier
# random forest

ada=AdaBoostClassifier(random_state=42)
ada.fit(X_train,y_train)
print('*'*20)

# prediction
train_prediction= ada.predict(X_train)
test_prediction= ada.predict(X_test)
print('*'*20)

# evaluation
from sklearn.metrics import accuracy_score
print('test accuracy:',accuracy_score(y_test,test_prediction))
print('train accuracy:',accuracy_score(y_train,train_prediction))
print('*'*20)

# cross validation score
from sklearn.model_selection import cross_val_score
score=cross_val_score(ada,X,y,cv=5)
print(score.mean())
print('*'*20)

#  prediction Summary by species
# print(classification_report(y_test, test_prediction))
print('*'*20)

# Accuracy score
ada_h = accuracy_score(test_prediction,y_test)
print(f"{round(ada_h*100,2)}% Accurate")

********************
********************
test accuracy: 0.915
train accuracy: 0.9175
********************
0.915
********************
********************
91.5% Accurate


In [23]:
from sklearn.ensemble import GradientBoostingClassifier
# random forest

gbc=GradientBoostingClassifier(random_state=42)
gbc.fit(X_train,y_train)
print('*'*20)

# prediction
train_prediction= gbc.predict(X_train)
test_prediction= gbc.predict(X_test)
print('*'*20)

# evaluation
from sklearn.metrics import accuracy_score
print('test accuracy:',accuracy_score(y_test,test_prediction))
print('train accuracy:',accuracy_score(y_train,train_prediction))
print('*'*20)

# cross validation score
from sklearn.model_selection import cross_val_score
score=cross_val_score(gbc,X,y,cv=5)
print(score.mean())
print('*'*20)

#  prediction Summary by species
# print(classification_report(y_test, test_prediction))
print('*'*20)

# Accuracy score
gbc_h = accuracy_score(test_prediction,y_test)
print(f"{round(gbc_h*100,2)}% Accurate")

********************
********************
test accuracy: 0.925
train accuracy: 0.936
********************
0.9236000000000001
********************
********************
92.5% Accurate


In [24]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# model
knn_model=KNeighborsClassifier()
knn_model.fit(X_train,y_train)

# prediction

train_prediction= knn_model.predict(X_train)
test_prediction= knn_model.predict(X_test)

# evaluation
print('*'*20)
from sklearn.metrics import accuracy_score
print('Test accuracy:',accuracy_score(y_test,test_prediction))
print('Train accuracy:',accuracy_score(y_train,train_prediction))

print('*'*20)
result = confusion_matrix(y_test, test_prediction)
print("Confusion Matrix:")
print(result)


print('*'*20)
#  prediction Summary by species
print(classification_report(y_test, test_prediction))


print('*'*20)
# Accuracy score
Knn_SC = accuracy_score(test_prediction,y_test)
print(f"{round(Knn_SC*100,2)}% Accurate")


********************
Test accuracy: 0.913
Train accuracy: 0.9315
********************
Confusion Matrix:
[[346  56]
 [ 31 567]]
********************
              precision    recall  f1-score   support

           0       0.92      0.86      0.89       402
           1       0.91      0.95      0.93       598

    accuracy                           0.91      1000
   macro avg       0.91      0.90      0.91      1000
weighted avg       0.91      0.91      0.91      1000

********************
91.3% Accurate


In [25]:
score = [DT_SC,RF_SC,lr_HSC,Knn_SC,XGB_HSC,ada_h,gbc_h]
Models = pd.DataFrame({
    'Model': ["Decision Tree","Random Forest", "Logistic Regression",'Knn','XGBoost','AdaBoost',"GradientBoostingClassifier"],
    'Score': score})
Models.sort_values(by='Score', ascending=False)

Model  Score
6  GradientBoostingClassifier  0.925
2         Logistic Regression  0.920
1               Random Forest  0.918
4                     XGBoost  0.918
5                    AdaBoost  0.915
3                         Knn  0.913
0               Decision Tree  0.886

In [26]:
import pickle
#save the model
model = DT  # Your machine learning model object
file_path = 'gbc_hearing.pkl'  # Path to the file where you want to save the model

with open(file_path, 'wb') as file:
    pickle.dump(model, file)


In [27]:
# load the model
import pickle

file_path = 'gbc_hearing.pkl'  # Path to the saved model file

with open(file_path, 'rb') as file:
    loaded_model = pickle.load(file)

In [28]:
X_train

age  physical_score  db  gender
2913  52.0            36.3  19       1
3275  52.0            35.5   0       0
775   62.0            19.4  24       1
217   48.0            34.7  10       1
1245  69.0            19.0  16       0
...    ...             ...  ..     ...
4931  59.0            24.4  13       1
3264  47.0            38.3   0       1
1653  58.0            30.6  19       1
2607  40.0            40.3  18       1
2732  59.0            36.9   4       1

[4000 rows x 4 columns]

In [24]:
loaded_model.predict([[19,36.3]])

d:\Codebook\Machine_Learning\env\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [28]:
loaded_model.predict([[39,25.3]])

d:\Codebook\Machine_Learning\env\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)